<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserCredentialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredentialsRepository extends EntityRepository
{
}
